# 1) Скопируй к себе коллекцию запросов в бек (если надо) и тестируй апи бека через postman
# 2) Нюанс: Даты должны быть не в формате 2006-01-20 15:06:02.000000, а в формате 2006-01-20T15:06:02Z
# 3) Скачай docker desktop и посмотри как скачать docker-compose утилиту
# 4) После всего этого разархивируешь zip бекэнда, и через консоль запустишь команду docker-compose up —build -d (На этом шаге можем созвониться, объясню)
# Финал - у тебя локально поднят бек

